### ISSUE TITLE
Collect code coverage during crawling

### ISSUE THREAD

**Issue by marco-c** [MozillaSecurity/site-scout#25]
It would be nice to collect code coverage data through crawling, to identify websites / pages which exercise code that is not normally exercised by fuzzing or automated tests.

(similar idea to https://github.com/mozilla/coverage-crawler, which never was productionized)

**Comment by tysmith** [comment]
Yeah I think we could make this work. Most of the tools required already existing in some form or another in our fuzzing tool box.

A few questions that come to mind are:
- Is this high priority?
- Which sites would you like to target? Top 100... top 10K?
- How frequently would you like up to date results?

**Comment by marco-c** [comment]
Not a high priority, it'd just be nice to have.

I have no idea reagarding the sites, which ones are you targeting with site-scout?
